### ISSUE TITLE
Library potentially broken

### ISSUE THREAD

**Issue by dontgitit** [theli-ua/pyHoNBot#6]
Hi, I've been using this library for a few months. It seems it broke with yesterday's patch though. Any ideas? Thanks!

**Comment by Ninja101** [comment]
b7851608f482651f643bc207738925cf8e844c6c

Updated to latest protocol version, does that fix it for you?

**Comment by dontgitit** [comment]
Yup, works now! Thank you very much!

BTW - what exactly does this license entail/how may I use this library? I added on to it; in essence, it connects to a Twitch.tv IRC channel and relays messages between the channel and the bot's owner. I wrote this so that I wouldn't have to look at my phone/second monitor to interact with my viewers.

May I distribute this? Should I just create a public fork on Github? Let me know!

P.S. I found one or two "bugs", but I don't have my fork under source control so I can't remember what I fixed.... from what I remember though, I had to comment out this line https://github.com/theli-ua/pyHoNBot/blob/master/bot.py#L56 to get it to work. The reason was that you made it read 2 bytes at a time, but I had to put it in a polling loop with the Twitch socket with a timeout of 1 second, and HoN was closing the connection (I guess because it was taking too long to respond). 

P.P.S. Thanks for the awesome library! How'd you two put this together? This is a fan project, not under Frostburn, right? How did you figure out all the packet-level things? Really cool stuff :)

**Comment by Ninja101** [comment]
The license allows you to distribute this provided: "copyright notices are retained unchanged and any distribution of this package, whether modified or not, includes this license text."

As for your issue, it seems you should probably have your Twitch socket + HoN socket in separate threads, if I understood your issue correctly.

Primarily coded by Theli, I helped out a bit. It's a fan project and was created by packet sniffing the HoN client to/from the chat server.

**Comment by Ninja101** [comment]
Also, if the bot stops connecting again after future HoN updates, open your HoN client and type "PrintChatProtocol" in console (Ctrl+F8) and update the integer in hon/packets.py if it was incremented.

**Comment by stevelegere** [comment]
Wireshark is your best friend here. Learn how to use the filter function,
and watch the hex for what packet IDs mean what, and what information is
captured in each case. Unfortunately there isn't really an
"all-encompassing" document which outlines/details the protocol, but you
can find bits and pieces scattered throughout the Web. I asked then-S2
staff if they would provide this documentation to the public; surprisingly
the answer was YES however I never heard back from them.

I concur with Ninja as to your connection issues; general accepted practice
is to put common code in a class/function/whatever and leave the specific
details to the individual implementation. In this case, separate the code
for the two different connection types. It might be easier to make them two
completely independent functions, and then find the commonalities and
refactor accordingly.

Cheers

**Comment by dontgitit** [comment]
Ideally they should be in separate threads, yeah :)
But reading the default bytes (4096) each time instead of 2 fixed the issue.

I've only used python in the past for simple scripts so I wasn't sure how hard it would be to set up a multi-threaded app. Especially since the two threads would have to communicate with each other. That's why I decided to just poll both in a loop. Basically, it looks like this...

```
while(True):
   hon_bot.asyncore.loop(timeout=1, count=1)
   twitch_bot.reactor.process_once(timeout=1)
```

Anyways... are you interested in having this in master? I can issue a PR if you'd like. 
You can kinda see at the end of the game here http://www.twitch.tv/craz_killa/v/20915280?t=1h40m11s that I have it notify me when people enter/leave my twitch, and I can reply to the bot to have it post to twitch (and it also notifies me of things people write). 
Feel free to stop by at some point while I'm streaming to see it live ;P
